### ISSUE TITLE
Command to tell if player is nicked

### ISSUE THREAD

**Issue by PepperLola** [PepperLola/playerinfo#1]
`/isnick` compares name retrieved from Mojang API with in-game name.

**Comment by PepperLola** [comment]
Usage would be `/isnick <username>`. It would first retrieve the UUID of a player with that name from the Mojang API. If that player doesn't exist, we know it's a nick. If it does, we need to check the Hypixel stats for that player using the Hypixel API. If the player doesn't exist (has never joined Hypixel), we know it's a nick.

**Comment by PepperLola** [comment]
The stats overlay shows if players are nicked, but it currently only works in BedWars and SkyWars. This command would be a nice addition.

**Comment by Finbarr-1** [comment]
Bedwars and Duels*

**Comment by PepperLola** [comment]
Finally done!
